const Dict = {
  Municipal_Clearance: "براءة ذمة بلدية",
  Photo_Seller_ID: "صور هويات البائعين",
  Contract_of_Sale: "عقد البيع",
  Kushan: "الكوشان",
  Photo_Buer_ID: "صور هويات المشترين",
  Land_Describtion: "وصف الارض",
  Financial_Clearance: "براءة ذمة مالية",
  sale: "حركة بيع قيد المعالجة",
  createdAt: "تاريخ تقديم المعاملة",
  mort: "معاملة رهن قيد المعالجة",
  Photo_of_citizen_ID: "صورةالهوية",
  Photo_of_Bank_ID: "صورة هوية مفوض البنك",
  Legal_Declaration: "قرار عدلي",
  Insurance_Bond: "سندات التأمين",
  authorization_Letter: "كتاب تفويض",
  Insurance_Request: "طلب تأمين",
  sort: "معاملة فرز قيد المعالجة",
  Transaction_Report: "تقرير معاملة",
  Detection_Report: "تقرير كشف",
  Change_Statment: "بيان تغيير",
  Area_Chart: "مخطط مساحة",
  Site_Plan: "مخطط موقع",
  Execution_Warrant_Book: "قرار تنفيذ",
  court_decision: "قرار محكمة",
  frag: "معاملة تجزئة قيد المعالجة",
  inhert:"معاملة ",
  Photo_Inheritors_ID: "صور هويات الورثة",
  Limiting_Legacy: "حصر الارث",
  Endorsements: "مصادقة",
  saleaccept: "حركات بيع مقبولة",
  salenotcomp: "معاملات بيع غير منجزة",
  salecomp: "معاملات بيع منجزة",
  salereject: "معاملات بيع مرفوضة",
  accept: "مقبولة",
  reject: "مرفوضة",
  comp: "منجزة",
  notcomp: "غير منجزة",
  sortaccept: "حركات فرز مقبولة",
  sortnotcomp: "معاملات فرز غير منجزة",
  sortcomp: "معاملات فرز منجزة",
  sortreject: "معاملات فرز مرفوضة",
  mortaccept: "حركات رهن مقبولة",
  mortnotcomp: "معاملات رهن غير منجزة",
  mortcomp: "معاملات  رهن منجزة",
  mortreject: "معاملات رهن مرفوضة",
  fragaccept: "حركات تجزئة مقبولة",
  fragnotcomp: "معاملات تجزئة غير منجزة",
  fragcomp: "معاملات تجزئة منجزة",
  fragreject: "معاملات تجزئة مرفوضة",
  inhertaccept: "حركات نقل ارث مقبولة",
  inhertnotcomp: "معاملات نقل ارث غير منجزة",
  inhertcomp: "معاملات نقل ارث منجزة",
  inhertreject: "معاملات نقل ارث مرفوضة",
  site_plan: "مخطط موقع",
  land_desc:"وصف الارض",
  saleosama:"معاملات البيع",
  mortosama:"معاملات الرهن",
  fragosama:"معاملات التحزئة",
  inhertosama:'معاملات نقل الارث',
  sortosama:'معاملات الفرز'
};
export default Dict;
